# Generated by Django 5.2.5 on 2025-08-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField()),
                ('cover_image_url', models.URLField()),
            ],
        ),
    ]
